version = 1

test_patterns = ["*_test.ts"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]
  style_guide = "google"
  dialect = "typescript"